# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'usingOpenCV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OpenCV'

  # Pods for usingOpenCV

  target 'usingOpenCVTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'OpenCV'

  end

  target 'usingOpenCVUITests' do
    # Pods for testing
  pod 'OpenCV'

  end

end
